name: no-text
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        ghc: ['latest', '7.10']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Update cabal package database
      run: cabal update
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Build
      # -optl-no-pie is a workaround for an issue with GHC 7.10.3:
      # https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/123
      run: cabal build --ghc-option=-optl-no-pie --ghc-option=-optc-no-pie -f-text prettyprinter:prettyprinter
